export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  AUXILIAR = 'ROLE_AUXILIAR',
  PACIENTE = 'ROLE_PACIENTE',
  FAMILIAR = 'ROLE_FAMILIAR',
  MEDICO = 'ROLE_MEDICO',
  ENFERMERO = 'ROLE_ENFERMERO'
}
